### ISSUE TITLE
Integración continua

### ISSUE THREAD

**Issue by faog** [faog/SCL008-md-links#32]
Realizar integración continua usando Travis o Circle CLI

**Comment by faog** [comment]
- Se debe habilitar integración continua de travis en el repositorio del proyecto md-links

**Comment by faog** [comment]
- Se debe crear el archivo `.travis.yml`, con la siguiente configuración:
```
sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  before_install:
  - npm update
  install:
  - npm install
  script:
  - npm test 
```
